server {
    listen 1973;
    root /data;

    location / {
        autoindex on;
        sendfile   on;
        sendfile_max_chunk 1m;
        tcp_nopush on;
        keepalive_timeout 65;
        add_header Access-Control-Allow-Origin *;
    }
}