[target.'cfg(target_os = "linux")']
rustflags = ['--cfg', 'getrandom_backend="linux_getrandom"']

[target.'cfg(target = "wasm32-unknown-unknown")']
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
